from enum import IntEnum
from http import HTTPStatus


class RetryableStatus(IntEnum):
    REQUEST_TIMEOUT = HTTPStatus.REQUEST_TIMEOUT
    TOO_MANY_REQUESTS = HTTPStatus.TOO_MANY_REQUESTS
    INTERNAL_SERVER_ERROR = HTTPStatus.INTERNAL_SERVER_ERROR
    BAD_GATEWAY = HTTPStatus.BAD_GATEWAY
    SERVICE_UNAVAILABLE = HTTPStatus.SERVICE_UNAVAILABLE
    GATEWAY_TIMEOUT = HTTPStatus.GATEWAY_TIMEOUT
